"""deleted key

Revision ID: e15de59cf6aa
Revises: 61317f112fc9
Create Date: 2024-06-19 10:38:31.657046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15de59cf6aa'
down_revision: Union[str, None] = '61317f112fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_table_user_id_fkey', 'test_table', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('test_table_user_id_fkey', 'test_table', 'clients', ['user_id'], ['id'])
    # ### end Alembic commands ###
